name: ddb_shard0_master_smf

workflow:
  name: wf-ddb-shard0-master-smf
  namespace: default

renderer: modular_chaos
network_expand_to_component_pods: false

targets:
  - id: ddb_shard0_master
    finder: ddb_shard_master
    shard: "0"

  - id: smf_pool
    finder: smf_pods

stages:
  - mode: parallel
    faults:
      - type: network_delay
        selectors:
          from: smf_pool
          to: ddb_shard0_master
        direction: both
        duration: 30s
        delay:
          latency: 300ms
          jitter: 300ms

      - type: network_loss
        selectors:
          from: smf_pool
          to: ddb_shard0_master
        direction: both
        duration: 30s
        loss:
          loss: "10"
          correlation: "0"

      - type: pod_kill
        target: ddb_shard0_master
        delay: 0ms
        duration: 1s

      - type: pod_kill
        target: smf_pool
        expand:
          mode: random
          count: 1
        delay: 100ms
        duration: 1s

wait_seconds: 40
cleanup: true
